language: java
jdk:
- oraclejdk8
services:
- mysql
addons:
  apt:
    sources:
    - mysql-5.7-trusty
    packages:
    - mysql-server
    - mysql-client
cache:
  directories:
  - "$HOME/.gradle"
before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('521') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
- sudo mysql_upgrade -u root -p521
- sudo service mysql restart
- chmod +x gradlew
before_script:
- mysql -u root -p521 -e 'CREATE DATABASE crown;'
- mysql -u root -p521 crown < src/test/resources/sql/crown.sql
script: ./gradlew clean build -x test
notifications:
  email:
    recipients:
    - caratacus@qq.com
