logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: org.crown.model
server:
  port: 8088
