logging:
  config: classpath:logback-spring.xml
mybatis-plus:
  global-config:
    db-config:
      field-strategy: not_empty
      id-type: auto
      db-type: mysql
    banner: false
    super-mapper-class: org.crown.common.framework.mapper.BaseMapper
    refresh: true
  mapper-locations: classpath:mapper/*Mapper.xml
  typeAliasesPackage: org.crown.model.entity,org.crown.model.dto
server:
  port: 8088
spring:
  jackson:
    time-zone: GMT+8
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
      FAIL_ON_EMPTY_BEANS: false
    deserialization:
      FAIL_ON_UNKNOWN_PROPERTIES: false
    default-property-inclusion: non_null
    mapper:
      PROPAGATE_TRANSIENT_MARKER: true
    parser:
      ALLOW_BACKSLASH_ESCAPING_ANY_CHARACTER: true
  liquibase:
    enabled: false
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/crown?characterEncoding=utf8&serverTimezone=Asia/Shanghai&useSSL=false
    username: root
    password: 521
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      auto-commit: false
      connection-timeout: 30000
      idle-timeout: 25000
      login-timeout: 5
      max-lifetime: 30000
      read-only: false
      validation-timeout: 3000
      maximum-pool-size: 15
      minimum-idle: 10

